SMODS.Sound({key = "aiko_note1", path = "aikoshen/note.ogg"})
SMODS.Sound({key = "aiko_note2", path = "aikoshen/note2.ogg"})
SMODS.Sound({key = "aiko_note3", path = "aikoshen/note3.ogg"})
SMODS.Sound({key = "aiko_note4", path = "aikoshen/note4.ogg"})
SMODS.Sound({key = "aiko_note5", path = "aikoshen/note5.ogg"})
SMODS.Sound({key = "aiko_note6", path = "aikoshen/note6.ogg"})

SMODS.Sound({key = "elmer_hey1", path = "aikoshen/elmer_hey.ogg"})
SMODS.Sound({key = "elmer_hey2", path = "aikoshen/elmer_heyheyhey.ogg"})
SMODS.Sound({key = "elmer_2", path = "aikoshen/elmer_2.mp3"})
SMODS.Sound({key = "elmer_3", path = "aikoshen/elmer_3.wav"})
SMODS.Sound({key = "elmer_slur", path = "aikoshen/elmer_slur.wav"})